### ISSUE TITLE
Example of reading a GRIB file in own project

### ISSUE THREAD

**Issue by Quba1** [noritada/grib-rs#1]
### Proposed Feature

I think it would be useful to add the example script presenting how to use this library to read a GRIB file in own project.

### Motivation

As the library code is rather complex, it is not straightforward how to use the library in own project. Moreover, even small libraries include short presentation how to use them. I believe that adding the example script would lower a level of technical knowledge necessary for using this library. Therefore the library could also be used by atmospheric scientists, who might not have as extensive technical knowledge as programmers.

### Additional Info

The example script could be included as `.rs` file in `examples` folder or as a code snippet in `README`.

**Comment by noritada** [comment]
Thank you very much for posting an issue! I agree with your opinion.

At this point, the basic functionalities are still missing, and I am still trying to make various operations possible, so the API is not in a good form yet. I will continue to improve the documentation and example scripts as well as preparing the API.

**Comment by noritada** [comment]
Thank you very much for posting the issue and I'm sorry that it has taken me so long to respond. I haven't had time to work on the project for a while.

I've prepared two example scripts with plenty of comments and hope that they may help users understand the API. Those scripts will be shipped with the v0.3.0 release tomorrow.

If you'd like to see other examples, please let me know in the issue. Also, since this library's API is still not fully functional and not easy to use, so any suggestions are welcome.
