### ISSUE TITLE
Release new crate version with updated dependencies

### ISSUE THREAD

**Issue by Quba1** [noritada/grib-rs#9]
### Motivation

Crate version published on crates.io is well behind the latest version of the crate in Github repo. Because of that, many latest features are missing (e.g. partial support of GFS files reading).

### Proposed Solution

Release a new version of the crate (should be probably 0.4.x due to upgraded Rust edition). This will also be a great occasion to update outdated dependencies.

### Additional Context

The impact of this release will probably be minimal as the crate has (unfortunately) not too much users. But can be advantegous by adding new features to the crate, showing on crates.io site that the crate is actively maintained and in result bringing new users.

**Comment by noritada** [comment]
Thank you very much for suggestions. I'd like to follow your suggestions.

I have made various incompatible changes in the development version.  Since I thought it would bring less inconvenience to users if I add a few more changes before releasing it, I had not released it.

However, since I have not been able to concentrate on development for a longer period of time than expected, I am going to release the current version. There has been a big gap between example scripts available on GitHub Web UI and the released version, and I think it is not a good situation.

As you write, I also think it would be better to release it periodically to show the continuous development attitude.
